version: "3.9"
services:


  lb:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8081:8080","9000:9000"]
    depends_on: [worker1, worker2, prometheus, grafana]

  worker1:
    image: hashicorp/http-echo
    command: ["-listen=:9001","-text=hello-1"]
    ports: ["9001:9001"]

  worker2:
    image: hashicorp/http-echo
    command: ["-listen=:9002","-text=hello-2"]
    ports: ["9002:9002"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
